name: Biome コードレビュー # ワークフローの日本語名

on:
  pull_request:
    # JavaScript/TypeScriptファイルが変更された場合にのみワークフローを実行
    # .obsidianで始まるディレクトリ以下の変更は無視する
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '!.obsidian*/**' # .obsidianで始まるディレクトリ以下のファイルを明示的に除外

jobs:
  biome:
    # ジョブの日本語名
    name: コード整形 / Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - # ステップの日本語名: コードをリポジトリからチェックアウト
        name: コードをチェックアウト
        uses: actions:checkout@v4

      - # ステップの日本語名: Biomeを使ってコードをレビューし、結果をプルリクエストにコメント
        name: Biomeでコードをレビュー
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # プルリクエストのレビューコメントとして結果を報告
          fail_on_error: true # Biomeがエラーを検出した場合、このステップを失敗させ、ジョブ全体も失敗させる
